GET http://localhost:3000/

###get all users

GET http://localhost:3000/api/users

###
###single user

GET http://localhost:3000/api/users/30

###delete user

DELETE  http://localhost:3000/api/users

###

GET http://localhost:3000/api/users/town

###

GET http://localhost:3000/api/users/drivers

###

POST http://localhost:3000/api/users
content-type: application/json

{
    "id": 5,
    "name": "kiskis",
    "town": "vilnius",
    "isDriver": false
}